# META Data
name: filsign_learn_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: '>=2.19.5 <3.0.0'


# Plugins
dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.3.0
  flutter_native_splash: ^2.2.19
  shared_preferences: ^2.0.20
  provider: ^6.0.5
  animated_text_kit: ^4.2.2
  lottie: ^2.3.1
  flutter_custom_clippers: ^2.1.0
  google_sign_in: ^6.0.2

# Splash Screen
flutter_native_splash:
  android: true
  ios: false
  web: true

  color: "#FFCD1F"
  image: "assets/images/splash.png"


  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/splash.png
    - assets/images/icon.png
    - assets/images/google_icon.png
    - assets/images/notification.png
    - assets/images/benefit1.png
    - assets/images/benefit2.png
    - assets/images/benefit3.png
    - assets/images/benefit4.png


    # Achivements
    - assets/images/achievement_first_time.png
    - assets/images/achievement_open_second_lesson.png
    - assets/images/achievement_first_taker.png
    - assets/images/achievement_streak.png
    - assets/images/achievement_GOAT.png


    # Active Lessons
    - assets/images/apple.png
    - assets/images/hat.png
    - assets/images/monke.png
    - assets/images/umbrella.png
    - assets/images/one.png
    - assets/images/6.png
    - assets/images/family.png
    - assets/images/family1.png
    - assets/images/house.png
    - assets/images/house_selected.png
    - assets/images/playground.png
    - assets/images/playground_selected.png
    - assets/images/profile.png
    - assets/images/profile_selected.png

    # Not Active Lessons
    - assets/images/apple_not_active.png
    - assets/images/hat_not_active.png
    - assets/images/monke_not_active.png
    - assets/images/umbrella_not_active.png
    - assets/images/one_not_active.png
    - assets/images/6_not_active.png
    - assets/images/family_not_active.png
    - assets/images/family1_not_active.png

    # Active sub lessons
    - assets/images/sublesson_welcome.png
    - assets/images/sublesson_END.png
    - assets/images/sublesson_END_not_active.png

    # ALPHABETS ACTIVE
    - assets/images/sublesson_A.png
    - assets/images/sublesson_B.png
    - assets/images/sublesson_C.png
    - assets/images/sublesson_D.png
    - assets/images/sublesson_E.png
    - assets/images/sublesson_F.png
    - assets/images/sublesson_G.png
    
    # ALPHABETS NOT ACTIVE
    - assets/images/sublesson_A_not_active.png
    - assets/images/sublesson_B_not_active.png
    - assets/images/sublesson_C_not_active.png
    - assets/images/sublesson_D_not_active.png
    - assets/images/sublesson_E_not_active.png
    - assets/images/sublesson_F_not_active.png
    - assets/images/sublesson_G_not_active.png

    # Profiles
    - assets/images/display_profile.png
    - assets/images/display_profile_1.png
    - assets/images/display_profile_2.png
    - assets/images/display_profile_3.png
    - assets/images/display_profile_4.png
    - assets/images/display_profile_5.png

    # Dialogs Icon
    - assets/images/warning_dialog.png
    - assets/images/success_dialog.png
    - assets/images/confirmation_dialog.png
    - assets/images/locked_dialog.png

    # Illustrations
    - assets/images/username_illustration.png

    # Lottie Files
    - assets/lottie/username.json
    - assets/lottie/benefit1.json
    - assets/lottie/benefit2.json
    - assets/lottie/benefit3.json
    - assets/lottie/background.json


  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka_Condensed-Bold.ttf
        - asset: assets/fonts/Fredoka_Condensed-Light.ttf
        - asset: assets/fonts/Fredoka_Condensed-Medium.ttf
        - asset: assets/fonts/Fredoka_Condensed-Regular.ttf
        - asset: assets/fonts/Fredoka_Condensed-SemiBold.ttf
        - asset: assets/fonts/Fredoka_Expanded-Bold.ttf
        - asset: assets/fonts/Fredoka_Expanded-Light.ttf
        - asset: assets/fonts/Fredoka_Expanded-Medium.ttf
        - asset: assets/fonts/Fredoka_Expanded-Regular.ttf
        - asset: assets/fonts/Fredoka_Expanded-SemiBold.ttf
        - asset: assets/fonts/Fredoka_SemiCondensed-Bold.ttf
        - asset: assets/fonts/Fredoka_SemiCondensed-Light.ttf
        - asset: assets/fonts/Fredoka_SemiCondensed-Medium.ttf
        - asset: assets/fonts/Fredoka_SemiCondensed-Regular.ttf
        - asset: assets/fonts/Fredoka_SemiCondensed-SemiBold.ttf
        - asset: assets/fonts/Fredoka_SemiExpanded-Bold.ttf
        - asset: assets/fonts/Fredoka_SemiExpanded-Light.ttf
        - asset: assets/fonts/Fredoka_SemiExpanded-Medium.ttf
        - asset: assets/fonts/Fredoka_SemiExpanded-Regular.ttf
        - asset: assets/fonts/Fredoka_SemiExpanded-SemiBold.ttf
        - asset: assets/fonts/Fredoka-Bold.ttf
        - asset: assets/fonts/Fredoka-Light.ttf
        - asset: assets/fonts/Fredoka-Medium.ttf
        - asset: assets/fonts/Fredoka-Regular.ttf
        - asset: assets/fonts/Fredoka-SemiBold.ttf
